### ISSUE TITLE
Release with ring 0.16

### ISSUE THREAD

**Issue by tekjar** [Keats/jsonwebtoken#109]
Hi. Are there any tentative dates to release `next` branch with ring 0.16?

**Comment by Keats** [comment]
No dates but there is an ongoing active work in https://github.com/Keats/jsonwebtoken/pull/107 which should result in an alpha version once the RSA pubkey components bug is fixed and the docs updated.

**Comment by Dowwie** [comment]
@Keats there's report that use of actix-web secure cookie feature triggers a ring version conflict with jsonwebtoken imported into the lib as well.  Aren't you using actix-web in your projects?

**Comment by Keats** [comment]
I'm not using actix-web anymore right now, and I have never used jsonwebtoken (this crate) myself.

> a ring version conflict with jsonwebtoken v7-alpha imported into the lib as well, due to using ring 0.16.

That's the reason why jsonwebtoken is on v7, every new release of ring is incompatible with the previous one and there can be only one in a project: the whole ecosystem needs to be updated. I *think* it's not a problem anymore since 0.16 though.

**Comment by Dowwie** [comment]
This has since been addressed in latest actix-X projects.  This means the new jsonwebtoken will work with actix-web v2.

**Comment by Keats** [comment]
Closing as there is the v7 alpha on crates io for now and full release shouldn't take too long.
