### ISSUE TITLE
Create a DecodingKey from jwks_url

### ISSUE THREAD

**Issue by sestrella** [Keats/jsonwebtoken#226]
I have been using the features on the next branch and I have to say that the [Auth0 example](https://github.com/Keats/jsonwebtoken/blob/next/examples/auth0.rs) was extremely handy. After digging a little bit into a similar [library](https://www.npmjs.com/package/jwks-rsa) (written in another language) I realized that it provides the availability to pull JWKS from a URL in fact Auth0 API exposes an endpoint for that, therefore, I wonder if it would make sense to introduce a function with the following type signature:

```rs
fn from_jwks_url(header: &Header, url: &str) -> Result<DecodingKey>
```

Under the hood, this function would take charge of:

- Request the provided `url` and parse the response body into a `JwkSet` struct (cache the result perhaps)
- Get the `kid` field out of the provided `header` (or pass the `kid` directly as an argument)
- Find the `Jwk` on the `JwkSet` matching the `kid`
- Build the `DecodingKey` from the `Jwk` found (call `from_rsa_components` perhaps)

I would be more than happy to submit a patch for this.

Reference:

https://auth0.com/docs/security/tokens/json-web-tokens/json-web-key-sets

**Comment by Keats** [comment]
I won't add any kind of HTTP request to this library as in Rust you would probably want to do it async and you need to select the executor/library. I'd rather let people handle the request however they want.
Also, you probably want to cache that http request in some ways and it's just easier if you handle it yourself: you can decide the policy.

**Comment by sestrella** [comment]
Fair enough, thank you for the feedback

**Comment by Cobular** [comment]
Sorry to open this again but I'm currently trying to implement auth0 RS256 and JWKS using this library and I'm a bit lost. I personally would prefer a more opinionated take on the requests and caching and whatnot since I'm not sure what the key refresh policy and the like should actually be in this setup, however I totally understand the library goals and the decision not to go that route.
However, I would still greatly appreciate an example of some kind implementing JWKS based keys where you pull from a URL and (what I'm mainly confused on) correctly refresh on error cases or something. Given that might be a bit too much to ask, would it be possible to update the documentation for JWKS to indicate how this update of the JWKS store should be done? Currently, the sections for [JWKS](https://docs.rs/jsonwebtoken/latest/jsonwebtoken/jwk/struct.JwkSet.html) and [JWK](https://docs.rs/jsonwebtoken/latest/jsonwebtoken/jwk/index.html) are both pretty sparse and IMO a bit of guidance could go a long way.

(I do see and am thankful for the example on JWKS with auth0, however my confusion stems around how to update the JWKS_REPLY. Should I check if there's a new version only if the kid on the incoming token is greater than any known kid in the JWKS? In other cases as well? I'm unsure if there are security implications here that I'm not seeing and I don't reallyyyy trust myself to do it right. Additionally, the mutable cache state is always a bit of a pain to work with so a bit more guidance / examples would be greatly appreciated)

**Comment by Keats** [comment]
> would it be possible to update the documentation for JWKS to indicate how this update of the JWKS store should be done?

Unlikely, I don't do that so I would just recommend to look at whatever doc they show for node/python and do the same.

**Comment by Cobular** [comment]
> > would it be possible to update the documentation for JWKS to indicate how this update of the JWKS store should be done?
> 
> Unlikely, I don't do that so I would just recommend to look at whatever doc they show for node/python and do the same.

Understandable, thank you! Last thing - does that wording mean you don't update the JWKS at all from the website in your applications? Is that viable? I'm unsure how quickly they get rotated.

**Comment by Keats** [comment]
>  you don't update the JWKS at all from the website in your applications?

No, I don't really use JWKs much and we do control our provider server (https://github.com/ory/hydra) so whatever we do doesn't really apply to Auth0/Okta etc
