### ISSUE TITLE
Bump untrusted version for security

### ISSUE THREAD

**Issue by tirkarthi** [Keats/jsonwebtoken#52]
Hi,

This project seems to use `untrusted = 0.5` as I can see from the cargo.toml file on master branch. Recently a security issue was fixed as part of 0.6.2 release. Please refer to https://github.com/RustSec/advisory-db/commit/3c0458d26bd19e30dc19ae5ca9a4540cc9c0394b . 

Kindly ignore if this is irrelevant or fixed on another branch.

Thanks.

**Comment by Keats** [comment]
Bumping it requires updating `ring` to an alpha version afaik though :/
Since only one version of ring is currently allowed in a project, it would be a breaking change to a version that lots of users might not be able to upgrade to and will need another breaking change to get rid of the alpha later.

@briansmith would you recommend updating to the alpha version of ring now or is the 0.13 release soonish?
